version: "3"
services:
  jupyter:
    image: jupyter/tensorflow-notebook
    ports: 
      - "127.0.0.1:8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks
      - ./audio:/home/jovyan/work/audio